###############################################################################
# Module: rds
# -----------------------------------------------------------------------------
# The "Shared state (SQL / session)" store from the diagram: a managed Postgres
# instance in private subnets. The DB password is generated by Terraform and
# stored in AWS Secrets Manager; ECS injects it into the backend as a secret
# env var (never rendered into a task definition in plaintext).
#
# Sized small and set to skip the final snapshot so it fits the proposal's
# ephemeral "create-and-destroy" model. Flip the flags for a real environment.
###############################################################################

# --------------------------------------------------------------------------- #
# Inputs. Only caller: `module "rds"` in modules/careroute_stack/main.tf, which
# has `count = var.enable_rds ? 1 : 0` — enable_rds is false in live/demo and
# live/staging, so today this module is NOT deployed anywhere.
# [TF] Because of that count, callers read outputs as module.rds[0].<output>.
# --------------------------------------------------------------------------- #

# Set by: local.name_prefix. Used in: subnet group, DB identifier, secret name.
variable "name_prefix" { type = string }
# Set by: module.networking.private_subnet_ids. Used in: aws_db_subnet_group.this.
variable "subnet_ids" { type = list(string) }
# Set by: [module.security.rds_sg_id] (the RDS SG). Used in: vpc_security_group_ids.
variable "security_group_ids" { type = list(string) }

# Postgres major.minor version. Set by: nobody — default "16.3".
variable "engine_version" {
  type    = string
  default = "16.3"
}

# DB instance class (burstable Graviton micro). Set by: var.db_instance_class
# (stack default "db.t4g.micro"; not overridden in live/).
variable "instance_class" {
  type    = string
  default = "db.t4g.micro"
}

# Storage in GiB. Set by: nobody — default 20.
variable "allocated_storage" {
  type    = number
  default = 20
}

# Initial database created inside the instance. Set by: nobody — default.
# Flows out via output db_name -> DB_NAME env var on the backend.
variable "db_name" {
  type    = string
  default = "careroute"
}

# Master username. Set by: nobody — default. Flows out via output username -> DB_USER.
variable "username" {
  type    = string
  default = "careroute_app"
}

# Multi-AZ = synchronous standby in a second AZ with automatic failover (~2x cost).
# Set by: var.db_multi_az (stack default false).
variable "multi_az" {
  type    = bool
  default = false
}

# Blocks deletion (incl. terraform destroy) until turned off.
# Set by: var.db_deletion_protection (stack default false).
variable "deletion_protection" {
  type    = bool
  default = false
}

# Set by: var.db_skip_final_snapshot (stack default true).
variable "skip_final_snapshot" {
  description = "true for ephemeral/staging (no snapshot on destroy); false for prod."
  type        = bool
  default     = true
}

# Set by: var.secret_recovery_window_days (stack variable; 0 by default).
variable "secret_recovery_window_days" {
  description = "Days the deleted db-credentials secret stays recoverable. 0 = delete immediately, which is what a create-and-destroy stack needs: a scheduled-for-deletion secret keeps its NAME reserved for the whole window, so the next apply cannot re-create `<prefix>/db-credentials`. Raise it for a real environment."
  type        = number
  default     = 0
}

# Set by: local.common_tags.
variable "tags" {
  type    = map(string)
  default = {}
}

# --------------------------------------------------------------------------- #
# Generated password -> Secrets Manager
# --------------------------------------------------------------------------- #
# [TF] random_password is from the `random` provider, not AWS: Terraform generates
# the value once and keeps it in STATE (so state itself is sensitive). .result
# is the generated string. Used by the DB instance, the secret and output password.
resource "random_password" "db" {
  length  = 24
  special = false # keep it URL/connection-string safe
}

# DB subnet group = the set of (private) subnets RDS may place the instance in;
# needs subnets in at least two AZs even for single-AZ.
resource "aws_db_subnet_group" "this" {
  name       = "${var.name_prefix}-db-subnets"
  subnet_ids = var.subnet_ids
  tags       = merge(var.tags, { Name = "${var.name_prefix}-db-subnets" })
}

# RDS DB instance (console: RDS > Databases), identifier "<prefix>-postgres".
# Consumed via outputs endpoint / port (backend DB_HOST/DB_PORT env vars and the
# MLflow store URI in careroute_stack).
resource "aws_db_instance" "this" {
  #checkov:skip=CKV_AWS_118:Enhanced monitoring needs an extra IAM role + bills CloudWatch Logs ingest; module has no consumer (enable_rds = false everywhere).
  #checkov:skip=CKV_AWS_129:Log exports create RDS-owned log groups with never-expire retention that survive terragrunt destroy (orphaned cost in a create-and-destroy stack). Add with a pre-created aws_cloudwatch_log_group when the DB gets a consumer.
  #checkov:skip=CKV2_AWS_30:Statement logging would write query text (potentially patient data) to CloudWatch, contradicting the redact-at-source stance (app/redact.py).
  identifier     = "${var.name_prefix}-postgres"
  engine         = "postgres"
  engine_version = var.engine_version
  instance_class = var.instance_class

  # gp3 SSD, encrypted at rest with the AWS-managed RDS KMS key.
  allocated_storage = var.allocated_storage
  storage_type      = "gp3"
  storage_encrypted = true

  db_name  = var.db_name
  username = var.username
  # Master password from random_password above (also written to the secret below).
  password = random_password.db.result

  # Private only: no public IP; reachable only through the RDS security group.
  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = var.security_group_ids
  publicly_accessible    = false
  multi_az               = var.multi_az

  # Free hardening (Checkov CKV_AWS_226 / CKV_AWS_161 / CKV2_AWS_60):
  # auto_minor_version_upgrade is already the provider default, stated so it is
  # auditable; IAM auth is additive (the password still works); snapshots keep
  # the cost-allocation tags.
  auto_minor_version_upgrade          = true
  iam_database_authentication_enabled = true
  copy_tags_to_snapshot               = true

  deletion_protection = var.deletion_protection
  skip_final_snapshot = var.skip_final_snapshot
  # Name of the final snapshot taken on destroy; null (omitted) when skipping it.
  final_snapshot_identifier = var.skip_final_snapshot ? null : "${var.name_prefix}-postgres-final"

  tags = merge(var.tags, { Name = "${var.name_prefix}-postgres" })
}

# Secret holds a JSON doc; ECS references individual keys with
# "<arn>:password::" so only the password becomes a container secret.
# Secrets Manager secret "<prefix>/db-credentials" (the container/metadata only;
# the value lives in the secret_version below). Readable by the ECS execution
# role because its policy allows "<prefix>/*" (modules/ecs_cluster).
resource "aws_secretsmanager_secret" "db" {
  name                    = "${var.name_prefix}/db-credentials"
  recovery_window_in_days = var.secret_recovery_window_days
  tags                    = var.tags
}

# The secret's actual value. [TF] jsonencode() makes the JSON string; referencing
# aws_db_instance.this.address makes Terraform write it only after the DB exists.
resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id
  secret_string = jsonencode({
    username = var.username
    password = random_password.db.result
    host     = aws_db_instance.this.address
    port     = aws_db_instance.this.port
    dbname   = var.db_name
  })
}

# --------------------------------------------------------------------------- #
# Outputs
# --------------------------------------------------------------------------- #
# [TF] Outputs = the module's return values, read as module.rds[0].<name>.
# endpoint -> backend DB_HOST, MLflow store URI, careroute_stack output rds_endpoint.
# port     -> backend DB_PORT (via tostring()) and the MLflow URI.
output "endpoint" { value = aws_db_instance.this.address }
output "port" { value = aws_db_instance.this.port }
# db_name / username -> backend DB_NAME / DB_USER and the MLflow URI.
output "db_name" { value = var.db_name }
output "username" { value = var.username }
# secret_arn -> careroute_stack output db_secret_arn.
output "secret_arn" { value = aws_secretsmanager_secret.db.arn }

# Marked sensitive so it is redacted in plan/apply output and in `terragrunt
# output`. Exposed at all only so the stack can assemble the MLflow backend-store
# URI and put THAT in its own secret — containers still receive the password by
# Secrets Manager reference, never as a task-definition value.
# [TF] sensitive = true: Terraform redacts the value in CLI output; it is still
# stored in plain text in state. Consumer: aws_secretsmanager_secret_version.mlflow_store.
output "password" {
  value     = random_password.db.result
  sensitive = true
}

# valueFrom string ECS uses to inject just the password as a container secret.
# "<arn>:password::" = <secret ARN>:<json key>:<version stage>:<version id>; empty
# stage/id = current version. Consumer: backend `secrets` DB_PASSWORD in careroute_stack.
output "password_secret_ref" { value = "${aws_secretsmanager_secret.db.arn}:password::" }
